redis:
  restart: always
  tty: true
  image: 192.168.43.10:5002/joe/redis
  stdin_open: true
pyapp:
  restart: always
  tty: true
  image: 192.168.43.10:5002/joe/python-redis-demo:$$BUILD_NUMBER$$
  links:
  - 'redis:'
  stdin_open: true
pyapplb:
  ports:
  - $$PORT_NUMBER$$:5000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - pyapp:pyapp
  stdin_open: true
  labels:
    appsoar.dashboard.entrypoint.python: http://{ip}:{port}/
